### ISSUE TITLE
Auth Option

### ISSUE THREAD

**Issue by kardespro** [VoidDevsorg/node-scrapper#1]
Merhaba Hocam

Mödülü Inceledim Belki Kaçırmış Ola Bilirim ama Sanırım "auth?" Optionunu desteklemeyen Proxyleri Kullanamıyoruz veya Kullana Biliyoruz Geri dönüş Yaparsanız Sevinirim

Sevgilerle , Nego :)

**Comment by clqu** [comment]
Proxy altındaki "host" ve "port" dışındaki tüm opsiyonlar isteğe bağlıdır. Types dizinindeki proxy yüzlerini incelediğinizde de bunu görebilirsiniz.

**Comment by kardespro** [comment]
Bilgilendirdiğiniz için Teşekkürler Clau Hocam

Sevgilerle , Nego  :)
